# .github/workflows/deploy.yml
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
          SUBDIR: llmcalc

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '22', cache: 'pnpm' }

      - run: pnpm install

      - run: |
          PUBLIC_URL=/${{SUBDIR}} pnpm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/llm_gpu_vram_calc
          destination_dir: ${{SUBDIR}}
          # keep_files:true
          force_orphan: true